version: '3'

services:
#  rpc:
#    container_name: rpc
#    build:
#      context: ./ServersRPC/RPC
#      dockerfile: Dockerfile
#    ports:
#      - "1234:1234"
#    networks:
#      - mylocal

  json-rpc:
    container_name: json-rpc
    build:
      context: ./ServersRPC/JSON-RPC
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    networks:
      - mylocal

  app:
    build:
      context: ./GEO_Service
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - mylocal
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./GEO_Service/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app
    networks:
      - mylocal

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - mylocal
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./GEO_Service/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
networks:
  mylocal:
    driver: bridge
    external: true