version: '3'

services:
  geocoder:
    container_name: RPC
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    networks:
      - mylocal_rpc

networks:
  mylocal_rpc:
    external: true