version: '3'

services:
  rpc:
    container_name: rpc
    build:
      context: ./RPC
      dockerfile: Dockerfile
    ports:
      - "1234:1235"
    networks:
      - mylocal_rpc

  json-rpc:
    container_name: json-rpc
    build:
      context: ./JSON-RPC
      dockerfile: Dockerfile
    ports:
      - "4321:4322"
    networks:
      - mylocal_rpc


networks:
  mylocal_rpc:
    driver: bridge
    external: true