// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: api/GeoService/geo.proto

package geo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GeoService_SearchService_FullMethodName         = "/geo.GeoService/SearchService"
	GeoService_GeocodeAddressService_FullMethodName = "/geo.GeoService/GeocodeAddressService"
)

// GeoServiceClient is the client API for GeoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoServiceClient interface {
	SearchService(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*AddressSearch, error)
	GeocodeAddressService(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*AddressGeo, error)
}

type geoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoServiceClient(cc grpc.ClientConnInterface) GeoServiceClient {
	return &geoServiceClient{cc}
}

func (c *geoServiceClient) SearchService(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*AddressSearch, error) {
	out := new(AddressSearch)
	err := c.cc.Invoke(ctx, GeoService_SearchService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoServiceClient) GeocodeAddressService(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*AddressGeo, error) {
	out := new(AddressGeo)
	err := c.cc.Invoke(ctx, GeoService_GeocodeAddressService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoServiceServer is the server API for GeoService service.
// All implementations must embed UnimplementedGeoServiceServer
// for forward compatibility
type GeoServiceServer interface {
	SearchService(context.Context, *SearchRequest) (*AddressSearch, error)
	GeocodeAddressService(context.Context, *GeocodeRequest) (*AddressGeo, error)
	mustEmbedUnimplementedGeoServiceServer()
}

// UnimplementedGeoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGeoServiceServer struct {
}

func (UnimplementedGeoServiceServer) SearchService(context.Context, *SearchRequest) (*AddressSearch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchService not implemented")
}
func (UnimplementedGeoServiceServer) GeocodeAddressService(context.Context, *GeocodeRequest) (*AddressGeo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeocodeAddressService not implemented")
}
func (UnimplementedGeoServiceServer) mustEmbedUnimplementedGeoServiceServer() {}

// UnsafeGeoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoServiceServer will
// result in compilation errors.
type UnsafeGeoServiceServer interface {
	mustEmbedUnimplementedGeoServiceServer()
}

func RegisterGeoServiceServer(s grpc.ServiceRegistrar, srv GeoServiceServer) {
	s.RegisterService(&GeoService_ServiceDesc, srv)
}

func _GeoService_SearchService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServiceServer).SearchService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoService_SearchService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServiceServer).SearchService(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoService_GeocodeAddressService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServiceServer).GeocodeAddressService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoService_GeocodeAddressService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServiceServer).GeocodeAddressService(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoService_ServiceDesc is the grpc.ServiceDesc for GeoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geo.GeoService",
	HandlerType: (*GeoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchService",
			Handler:    _GeoService_SearchService_Handler,
		},
		{
			MethodName: "GeocodeAddressService",
			Handler:    _GeoService_GeocodeAddressService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/GeoService/geo.proto",
}
